name: Docker build CPU

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: crpi-7u9ufs69jsthup8p.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - 
        name: Set tag
        id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "::set-output name=tag::${{ github.event.release.tag_name }}"
          else
            echo "::set-output name=tag::latest"
          fi

      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: crpi-7u9ufs69jsthup8p.cn-hangzhou.personal.cr.aliyuncs.com/tts2024xz/xz_tts2024:${{ steps.set_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
